---
title: Hayaza.Github.Io
timezone: Asia/Jakarta
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
lsi: false
exclude:
- script
- vendor
- Gemfile
- Gemfile.lock
- config.ru
- Procfile
- Rakefile
- readme.md
- scss
permalink: "/blog/:title"
markdown_ext: markdown,mkd,mkdn,md
name: Azmi Hayaza's Blog
description: The personal site of Azmi Abdulkarim Hayaza, data-driven marketing professional.
  Where I write about marketing, technology, strategy and in between.
url: http://www.ahayaza.com
gems:
- jekyll-redirect-from
sass:
  sass_dir: _sass
  style: compressed
